module.exports = [
  {
    name: `Lorem 1`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 100,
    img: `https://picsum.photos/150/150`,
    category: `Type One`,
  },
  {
    name: `Lorem 2`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 100,
    img: `https://picsum.photos/150/150`,
    category: `Type One`,
  },
  {
    name: `Lorem 3`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 100,
    img: `https://picsum.photos/150/150`,
    category: `Type Three`,
  },
  {
    name: `Lorem 4`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 100,
    img: `https://picsum.photos/150/150`,
    category: `Type Two`,
  },
  {
    name: `Lorem 5`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 100,
    img: `https://picsum.photos/150/150`,
    category: `Type Two`,
  },
  {
    name: `Lorem 6`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 100,
    img: `https://picsum.photos/150/150`,
    category: `Type Two`,
  },
  {
    name: `Lorem 7`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 100,
    img: `https://picsum.photos/150/150`,
    category: `Type Two`,
  },
  {
    name: `Lorem 8`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 100,
    img: `https://picsum.photos/150/150`,
    category: `Type Three`,
  },
  {
    name: `Lorem 9`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 100,
    img: `https://picsum.photos/150/150`,
    category: `Type Three`,
  },
  {
    name: `Lorem 10`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 100,
    img: `https://picsum.photos/150/150`,
    category: `Type Three`,
  }, {
    name: `Lorem 11`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 200,
    img: `https://picsum.photos/150/150`,
    category: `Type One`,
  },
  {
    name: `Lorem 12`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 201,
    img: `https://picsum.photos/150/150`,
    category: `Type One`,
  },
  {
    name: `Lorem 13`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 202,
    img: `https://picsum.photos/150/150`,
    category: `Type Three`,
  },
  {
    name: `Lorem 14`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 204,
    img: `https://picsum.photos/150/150`,
    category: `Type Two`,
  },
  {
    name: `Lorem 15`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 219,
    img: `https://picsum.photos/150/150`,
    category: `Type Two`,
  },
  {
    name: `Lorem 16`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 372,
    img: `https://picsum.photos/150/150`,
    category: `Type Two`,
  },
  {
    name: `Lorem 17`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 452,
    img: `https://picsum.photos/150/150`,
    category: `Type Two`,
  },
  {
    name: `Lorem 18`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 76,
    img: `https://picsum.photos/150/150`,
    category: `Type Three`,
  },
  {
    name: `Lorem 19`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 570,
    img: `https://picsum.photos/150/150`,
    category: `Type Three`,
  },
  {
    name: `Lorem 20`,
    description: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus exercitationem quaerat sit esse sed mollitia molestiae sapiente temporibus obcaecati quod, impedit asperiores voluptate suscipit odit a maiores numquam vitae nostrum!`,
    price: 890,
    img: `https://picsum.photos/150/150`,
    category: `Type Three`,
  },
];
